name: wifi
description: Flutter plugin providing WiFi.
homepage: https://github.com/once10301/wifi
version: 0.1.5

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ^0.1.2

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ly.wifi
    pluginClass: WifiPlugin

